### ISSUE TITLE
differentiate comparator and display type

### ISSUE THREAD

**Issue by zachll** [Display-Lab/card-study#10]
Add a comparator specification to the cards that is independent of the display type. It appears that currently the bar chart uses a goal comparator and the line chart uses a peer comparator.

**Comment by grosscol** [comment]
Addressed by e821260c8ed7d3d6128208da316ea8fa248b1196
Adds a `comparator_title` parameter to the `run()` methods of the line and bar charts.  The comparator title can be specified.  E.g. in card01:
 https://github.com/Display-Lab/card-study/blob/e821260c8ed7d3d6128208da316ea8fa248b1196/cards/card01.Rmd#L68

**Comment by grosscol** [comment]
The "comparators" aren't calculated.  They're hard coded.

In the line chart:
https://github.com/Display-Lab/card-study/blob/e821260c8ed7d3d6128208da316ea8fa248b1196/cards/fig_comp_line.R#L25

In the bar chart:
https://github.com/Display-Lab/card-study/blob/e821260c8ed7d3d6128208da316ea8fa248b1196/cards/fig_single_bar.R#L11
