### ISSUE TITLE
move closing email statements to include script

### ISSUE THREAD

**Issue by zachll** [Display-Lab/card-study#12]
Move identical text that appears 32 times at the closing statements of the emails into a single location to enable easier editing:

"A case-by-case breakdown of your results are available at your [clinical quality dashboard](https://www.aspirecqi.org/HIEBus/identityserver/local/login?signInId=2b0fc382a1904b699377c926723c9eb4).

More information about the rationale for the measure PONV 03 and how it is calculated [are available here](https://spec.mpog.org/Spec/Public/33).

Sincerely,

The MPOG Quality Team"

**Comment by grosscol** [comment]
Moved signoff to LaTeX macro defined in `preamble.tex`.
Modified paragraph indentation size for entire document to avoid having to get `\noindent` to work within a macro.

Closed by 3afcf7ade17fe962e7250648938d448bf4bafa31
