### ISSUE TITLE
create time-point bar chart

### ISSUE THREAD

**Issue by zachll** [Display-Lab/card-study#13]
create a time-point bar chart display that accepts one time interval as input and which can show a goal or peer comparator

**Comment by grosscol** [comment]
Per 10am meeting:

## Reqs
- Pull most recent time point of data set. 
- X-axis labeled ascribee as "You"
- Numerator/Denominator count on top of the bar.
- No legend.
- Modify existing bar chart to new template.

## Nice to have
- Print comparator title adjacent to line in graph area.
  - Remove legend in favor of above label of comparator

**Comment by grosscol** [comment]
Closed by e07110b501465e46724ffece957780fdcaf40999
